### ISSUE TITLE
Suggestion about the tags

### ISSUE THREAD

**Issue by YivanLiu** [CaptainArbitrary/CompactWorkTab#26] opened 2023-08-30 02:25 UTC
![image](https://github.com/CaptainArbitrary/CompactWorkTab/assets/90629260/7c6a86db-eb89-491c-a45f-8b8c7a0eedc7)
It would be better if an alternative config was added to make the work tags incline, like the tags in the scientific chart.

**Comment by jefferyharrell** [comment] 2023-08-30 03:28
Thanks! This is a duplicate of #23. Closing as such.

**Closed as completed by jefferyharrell** 2023-08-30 03:28 UTC
Labels: duplicate
